### ISSUE TITLE
letter registers are not show properly on some themes

### ISSUE THREAD

**Issue by Rizhiy** [tversteeg/registers.nvim#108]
### Are you willing to implement this yourself?

Yes

### Please select which platform you are using

Linux

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Letter registers are not shown properly. e.g.
![image](https://github.com/tversteeg/registers.nvim/assets/5617397/d8c6bbf1-b3cd-43a3-856b-0b5fe1d937e0)
As can be seen there are letter registers for which the key is not shown.
(a register is selected, but otherwise it would not be visible as well)

I'm using gruvbox colorscheme

### Neovim version

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

### Setup

```lua
return {
    "tversteeg/registers.nvim",
    keys = {
        { '"', mode = { "n", "v" } },
        { "<C-R>", mode = "i" },
    },
    cmd = "Registers",
    config = function()
        local registers = require("registers")
        registers.setup({
            window = {
                border = require("rizhiy.border").Border(),
                transparency = 0,
            },
            bind_keys = {
                registers = registers.apply_register({ keep_open_until_keypress = true }),
            },
        })
    end,
}
```

**Comment by tversteeg** [comment]
Thanks for the report. Any PRs to fix this are welcome!

**Comment by Rizhiy** [comment]
Hi, thank you. I guess I forgot to RTFM)
I managed to fix it by setting `named` item.

The cause was that my `Todo` highlight is nearly black: `Todoxxx cterm=bold,italic gui=bold,italic guifg=#282828`.
This seems to be set by https://github.com/folke/todo-comments.nvim
