### ISSUE TITLE
Popup stays open on focus lost

### ISSUE THREAD

**Issue by rudotriton** [tversteeg/registers.nvim#11]
If I open the popup with `"` in normal mode and were to click on the underlying buffer, the popup stays open. The next time i press `"` again, a new one is created and this can be repeated ad infinitum.

The first time I accidentally ran into it, any keypress would throw me an invalid window id error so there wasn't even a way to get away from it.

Maybe the popup should be closed when the user clicked (unusual with vim, I know) somewhere outside the popup, or at least check that there is at most one popup open?

For illustrative purposes:

![registers](https://user-images.githubusercontent.com/14181026/114515928-9025b980-9c45-11eb-88f6-cccc5831d748.png)

**Comment by rnevius** [comment]
This also happens for me if I just press `<C-r>` twice in a row while in insert mode.

**Comment by rnevius** [comment]
@tversteeg this isn't fixed if focus of the original window is lost when invoking the registers window a second time (see my above comment).
