### ISSUE TITLE
Error when invoking Registers at the end of file.

### ISSUE THREAD

**Issue by mvargasmoran** [tversteeg/registers.nvim#12]
After opening a file in nvim I do a `GG` to paste something in the bottom of the file then `:Registers` and get this error:
```
E5108: Error executing lua ...os/.config/nvim/plugged/registers.nvim/lua/registers.lua:161: 'height' key must be a positive
 Integer
Press ENTER or type command to continue
```
Guess it's just that it doesn't fit within the screen.

![image](https://user-images.githubusercontent.com/5852003/114516972-e0802580-9c0b-11eb-9ce5-3eb7082fb764.png)

**Comment by tversteeg** [comment]
I can't reproduce this, I just get a single line that's hard to read (another issue) but I don't get an error.. Are you using the latest version?

**Comment by mvargasmoran** [comment]
I'm using:
NVIM v0.5.0-dev+48e8057
And installed the plugin about 2 hours ago using vim-Plug.

**Comment by mvargasmoran** [comment]
UwU) (UωU ) Is a really nice plugin.

**Comment by tversteeg** [comment]
Thank you ^^
