### ISSUE TITLE
Text garbled when using the plugin

### ISSUE THREAD

**Issue by Seich** [tversteeg/registers.nvim#17]
Before anything I want to mention I love this plugin. Thanks for creating it! 

I have a weird issue and I am not sure how to even begin debugging it. When using the plugin my text gets pushed around and... garbled? This doesn't happen when pasting from a register directly which is weird. Any advice?

Here's a GIF that'll hopefully make it clearer, I am having a hard time describing it accurately.

![registers](https://user-images.githubusercontent.com/206451/114824285-e861d600-9d81-11eb-870d-847af5e7ce79.gif)

**Comment by tversteeg** [comment]
That's interesting, haven't encountered that before. What other plugins are you using? It might be the case that they interfere with each other in some weird way..

**Comment by Seich** [comment]
That's probably it, I'll create a minimal config and get back to you.

**Comment by tversteeg** [comment]
Will you send the config or should I close the issue?

**Comment by Seich** [comment]
Sorry, I haven't had the time to really dig into it. I'll go ahead and close it for. Thanks.
