### ISSUE TITLE
Output is incorrect when using <Ctrl-R>

### ISSUE THREAD

**Issue by sQVe** [tversteeg/registers.nvim#18]
Hey 👋🏼,

Cheers for creating this plugin. 🍻 

I noted a somewhat nasty bug today when trying to do a lot of color replacements. I *yank* a color with `ye` and when move the cursor to the beginning of the color I want to replace and run `ce<c-r>0`. The yanked color is pasted but not at the correct stop. See attached gif.

![Peek 2021-05-20 08-43](https://user-images.githubusercontent.com/2284724/118932049-e4f4d800-b947-11eb-965f-b054b14a6e97.gif)

**Comment by tversteeg** [comment]
Thanks for the report!

**Comment by sQVe** [comment]
@tversteeg Cheers for the quick fix 🍻

**Comment by sQVe** [comment]
I just tried reinstalling this and I'm still getting the same issues.

**Comment by tversteeg** [comment]
You're right, I thought I fixed it but it still seems to happen when the cursor's at the second to last position of a line.

**Comment by tversteeg** [comment]
I think I need help with this issue, I have no idea how to get the actual last column in insert mode. What I tried is this, but it's not working all the time:

```lua
-- Temporarily set the virtualedit to all so we can get the proper insert position, see :h col
local used_virtualedit = vim.api.nvim_get_option("virtualedit")
vim.api.nvim_set_option("virtualedit", "all")

-- Compare the cursor positions to see if we are at the end of the line
cursor_is_last = vim.api.nvim_call_function("col", {"."}) == vim.api.nvim_call_function("col", {"$"})

-- Set the virtualedit mode back
vim.api.nvim_set_option("virtualedit", used_virtualedit)
```

**Comment by QiBaobin** [comment]
Please test if below PR fixed this issue, @tversteeg , @sQVe 

[Fix cursor_is_last issue](https://github.com/tversteeg/registers.nvim/pull/21)

**Comment by sQVe** [comment]
Getting this now when trying: `E5108: Error executing lua ...ocal/share/nvim/plugged/registers.nvim/lua/registers.lua:295: Vim:Error executing lua callback: [string ":lua"]:1: Vim(call):E16: Invalid range:  call
s:RemoveRange(start, end) | endif`

**Comment by tversteeg** [comment]
@sQVe What did you do to get that? Can you reproduce it?

**Comment by sQVe** [comment]
For file:

```
'foo'
'bar'
```
Run: `gg0ffyejce<Ctrl-R>+`

**Comment by tversteeg** [comment]
Unfortunately that's working fine with me, I don't get any errors..

**Comment by sQVe** [comment]
It doesn't work if the file ends on `'bar'` for me, otherwise it's fine. Test with attached file.

[example-file.txt](https://github.com/tversteeg/registers.nvim/files/6555091/example-file.txt)

**Comment by tversteeg** [comment]
That's exactly what I tested it with as well.

**Comment by QiBaobin** [comment]
@sQVe , could you paste what's your registers? Maybe it's related with the content of your `+` register.
