### ISSUE TITLE
pmenu does not conform to list of registers

### ISSUE THREAD

**Issue by McAuleyPenney** [tversteeg/registers.nvim#20]
Firstly, thank you for this plugin! I use the registers a fair bit and this is useful for me!

The issue:
What:
   - The popup window does not conform to the list of registers in it **for me**. I fully appreciate that this may not be an issue with the plugin and that I may be missing a configuration somewhere. 

![image](https://user-images.githubusercontent.com/59481467/119379198-06b9cc00-bc74-11eb-8dab-a86f519e6f3f.png)

**Comment by tversteeg** [comment]
Interesting, haven't seen this before. Can you share your configuration?

**Comment by McAuleyPenney** [comment]
I am using only the standard "use" line for packer. I should have included that immediately, my mistake

![image](https://user-images.githubusercontent.com/59481467/119388500-37533300-bc7f-11eb-8696-1a1c950149f7.png)

**Comment by tversteeg** [comment]
Oh no I mean the complete configuration in general, there might be another plugin or setting that interferes with this one.

**Comment by McAuleyPenney** [comment]
Oh I see, my bad! This is how it was immediately before incorporating registers.nvim

https://github.com/McAuleyPenney/dotfiles/blob/29ae5430335ef27258a620c5da3c36be487fc6ff/nvim/Lua_build/lua/plugs/plugins.lua

**Comment by tversteeg** [comment]
I've found the culprit, the line `scrolloff=60` seems to cause the big size. What's the reason for setting it?

**Comment by McAuleyPenney** [comment]
I use scrolloff to keep the cursor centered. It's useful for keeping the context of what I'm writing in view, one of my more favored settings unfortunately

**Comment by tversteeg** [comment]
Interesting, never heard of that. I tried it, and it's a pretty nice setting.

**Comment by McAuleyPenney** [comment]
@tversteeg Just synced the new commit! Thank you!
