### ISSUE TITLE
Unable to append register with plugin enabled

### ISSUE THREAD

**Issue by gyvess** [tversteeg/registers.nvim#23]
Pressing `"X` results in `E21: Cannot make changes, 'modifiable' is off`.

**Comment by tversteeg** [comment]
Thanks for the report.

**Comment by gyvess** [comment]
Still doesn't work properly. The plugin now allows you to believe it was copied properly, however when you input the `"X` it is instead entered as `"x`. This overwrites what was previously in the register instead of appending.

**Comment by tversteeg** [comment]
My bad, I wasn't aware of the append functionality with uppercase characters.

**Comment by Frederick888** [comment]
There's maybe a regression? I'm using neovim 0.6.1 & registers.nvim c66458fe5f83b57d40b678058a8eeb6340f9275c with minimal vimrc below

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin('~/.vim/plugged')
Plug 'tversteeg/registers.nvim', { 'branch': 'main' }
call plug#end()
```

Then for instance `nvim test.txt`, add a few lines to the buffer, `:set nomodifiable`, try to `"ayy` and I can see the same error.

**Comment by lourenci** [comment]
Is there maybe another regression of this? I'm not being able to append to registers on `nvim 0.9` and 89257848124a3feb89963457ed9b3d90359dfe89.

**Comment by tversteeg** [comment]
@lourenci there has been another regression with the append register, thank you for noticing it. It should work now in the latest commit, can you confirm that it works?

**Comment by lourenci** [comment]
Fixed. Tks.
