### ISSUE TITLE
Not compatible with vim-scripts/ReplaceWithRegister

### ISSUE THREAD

**Issue by jdsutherland** [tversteeg/registers.nvim#25]
https://github.com/vim-scripts/ReplaceWithRegister allows `"*gr` with a motion for replacing with system clipboard. Unfortunately, it doesn't work with this plugin. I noticed that https://github.com/junegunn/vim-peekaboo has similar behavior and mappings to this plugin but it is compatible with vim-scripts/ReplaceWithRegister. Anyway, I'd prefer to use registers.nvim if it could made compatible.

**Comment by tversteeg** [comment]
Thanks for the report, I'll see how I can fix that.

**Comment by tversteeg** [comment]
I tried the plugin, but it seems to work fine for me? What part isn't compatible?

**Comment by jdsutherland** [comment]
Sorry, I should have been more clear. `"*gr` works by itself but it doesn't with a map like:
1. `nmap ,gr "*gr`. 

I don't have this problem with vim-peekaboo: https://github.com/junegunn/vim-peekaboo/blob/cc4469c204099c73dd7534531fa8ba271f704831/plugin/peekaboo.vim. I'm not sure if it's just a simple mapping thing but I tried tweaking things and couldn't get it to work. It appears that the `"` map from registers.nvim breaks the previously mentioned map (`1.`), but I don't have this problem with the exact same config except vim-peekabo swapped for registers.nvim.

**Comment by tversteeg** [comment]
Thanks for the research, I've been looking at it, but I can't find the problem yet.

The weird thing is that when I use a single character for the `nmap` (`nmap , "*gr` for example) everything works as expected, but when I change it to `,gr` it doesn't anymore..

I'll take a look later again.

**Comment by tversteeg** [comment]
The same fix for #33 also fixed this issue.

**Comment by jdsutherland** [comment]
The issue persists after adding the delay. I think this problem is different than #33.

**Comment by tversteeg** [comment]
What did you do to get the result? I've tested it with the map I posted above and it worked on my machine.

**Comment by jdsutherland** [comment]
I tried the previously mentioned map (`nmap ,gr "*gr`) and what you mentioned (`nmap , "*gr`). It looks like it's replacing with register `0`.

Are you sure that in your tests it's using the system clipboard? I still think the problem is that the `"` in the map is breaking. If you look at the above peekaboo issues, it looks like they had to hack some workarounds to make mappings work. I think this is supported by the fact that registers.nvim doesn't work with macro replay (seemingly for the same reason peekaboo didn't until they added those workarounds).
