### ISSUE TITLE
Cannot visualise current line if window is too large

### ISSUE THREAD

**Issue by akinsho** [tversteeg/registers.nvim#3]
Firstly thanks for making this. I really like `peekabo` and I really like your re-imagining of this functionality and the plan for it to be unobtrusive.

I just downloaded it and noticed something. When I have a lot of registers populated the window opened is quite large and moves the cursor several rows up covering up my current line

![image](https://user-images.githubusercontent.com/22454918/110918398-08c9eb00-8313-11eb-86eb-16813094a72c.png)

It makes it harder to know what I actually meant to get out of the register since I can no longer see the line I opened it from. The examples in your README show a less populated registers buffer so it stays below the cursor line. I wonder if it'd be possible to calculate how much space there was above or below and open it where there is more space although since technically you can have 26+9+x registers it might be better to truncate at a certain point and add the ability to scroll the window.

**Comment by tversteeg** [comment]
Thanks a lot, this is definitely a bug. I'll try to find a solution to make it scrollable when the registers don't fit. 

I also never heard of `peekabo` before. 😅

**Comment by akinsho** [comment]
@tversteeg that's really funny I just assumed this was based on that plugin, [heres a link](https://github.com/junegunn/vim-peekaboo). It's by the indomitable junegunn 😄 , but it has some bugs and I think june is quite busy and unable to make any fixes and not currently merging PRs so it's a little dead

**Comment by tversteeg** [comment]
That also looks like a nice implementation, it's a shame it's not maintained anymore. Although I personally do prefer a popup. There's also this implementation which also has a bit more organized buffer: https://github.com/gennaro-tedesco/nvim-peekup 

I also accept PRs!

**Comment by akinsho** [comment]
I had a look at `nvim-peekup` but I think a floating window that covers up your entire buffer defeats the point to me. I think it should be a little like a tooltip it appears near the line so you can *see* the line and decide which register you need to pull from. Maybe I just have a short attention span 😆 .

My strategy is to generally contribute things like this when I hit them in new plugins but I've currently spread myself *way* too thin on several projects of my own and others with this strategy so I don't think I'd be able to do it myself anytime soon 😓

**Comment by tversteeg** [comment]
I didn't mean to imply that you need to create a PR for this issue, just that if someone will submit PRs even though I'm not actively developing anymore I'll still review them. :)

The issue should be fixed now, can you verify that?

**Comment by akinsho** [comment]
@tversteeg thanks for looking into it so quickly 👍🏿 I just tried it out and I get `E5108: Error executing lua .../site/pack/packer/start/registers.nvim/lua/registers.lua:158: 'height' key must be a positive Integer` on pressing `"` now.

**Comment by tversteeg** [comment]
Sorry about that, should be fixed now!

**Comment by akinsho** [comment]
Just tried it now @tversteeg that resolved the issue 👍🏿 thanks 😄 . This is isn't a current concern at all but with this truncation a user cant see beyond whatever the limit is. say it truncates at register `e` you won't see anything beyond that which is fine from a truncation standpoint but maybe eventually there could be a mapping to scroll up and down. A few other plugins like `nvim-compe` and `lspsaga` do it.

Don't mean to pile on requests though just mentioning as a future consideration. Thanks for adding this 💯

**Comment by tversteeg** [comment]
I think that already works when you use the arrow keys, right? Maybe I can try different keys for that as well..

**Comment by akinsho** [comment]
Ah didn't realise I could use those I've mapped them to `<nop>` for years. Will try those.

**Comment by akinsho** [comment]
Just saw the recent change 😍 thanks so much for adding that 🚀
