### ISSUE TITLE
The option g:registers_window_border does not work.

### ISSUE THREAD

**Issue by jdhao** [tversteeg/registers.nvim#30]
It seems that I can not change the border of floating window via this option.

minimal init.vim:

```
set runtimepath+=/home/haojiedong/.local/share/nvim/site/pack/packer/start/registers.nvim
" double does not work neither
let g:registers_window_border = "single"
```

nvim -u init.vim

If we press `"` in normal mode, the floating window still does not have a nice single line border.

+ nvim version: 0.5.0
+ OS: Linux CentOS 7.4

**Comment by tversteeg** [comment]
Thanks for the report, it should be fixed now.
