### ISSUE TITLE
Option to change floating window background color

### ISSUE THREAD

**Issue by jdhao** [tversteeg/registers.nvim#31]
Currently, the background color of floating window is hardly discernable from the main window background color, making it difficult to know the boundary between them. It would be great to give the user a choice to change the background highlight of this floating window.

**Comment by MuhammadSawalhy** [comment]
I hope anyone can fix this, I don't know to code I Lua or VimScript D':

**Comment by tversteeg** [comment]
I've added a highlight group to the floating window, for example you can do the following now:

```vim
:hi RegistersWindow ctermbg=blue
```

**Comment by ivankovnatsky** [comment]
```vim
hi RegistersWindow ctermbg=blue guibg=blue
```
