### ISSUE TITLE
Feature Request: delay pop-up

### ISSUE THREAD

**Issue by andrewferrier-ibm** [tversteeg/registers.nvim#33]
registers.nvim looks great and I would look forward to using it as a replacement for https://github.com/junegunn/vim-peekaboo.

However, one thing that blocks me from doing that is a delay in the pop-up. Probably 75% of the time I know which registers I want and the pop-up is just a distraction. It would nice if I could configure a delay (e.g. 500ms) before the pop-up appears, which allows me to see the registers only if I pause for a moment's indecision.

Great work though, looks great so far!

**Comment by tversteeg** [comment]
Hi @zhengpd, this doesn't seem related to the current issue. Can you create a new issue for that?

**Comment by zhengpd** [comment]
> Hi @zhengpd, this doesn't seem related to the current issue. Can you create a new issue for that?

At first I thought it was the pop-up blocking the `"+y` sequence, which might be solved by introducing an option for delaying pop-up. Now I guess it's more related to the `"` key mapping itself. Allowing mapping to another key other than `"` could solve it. I'll create new issue.

**Comment by zhengpd** [comment]
Hi @tversteeg, after a second check on vim-peekaboo, I believe it's still related to the "delay" feature...Peekaboo's `peekaboo_delay` option doesn't break `vmap <C-c> "+y`, implementing via a timeout logic at https://github.com/junegunn/vim-peekaboo/blob/master/autoload/peekaboo.vim#L156

Maybe similar timeout logic could be added to Registers.

**Comment by tversteeg** [comment]
@zhengpd did this also fix your issue?

**Comment by zhengpd** [comment]
> @zhengpd did this also fix your issue?

@tversteeg Yes I'm using the above script, works well.

**Comment by zhengpd** [comment]
Strang. Just updated to https://github.com/tversteeg/registers.nvim/commit/3ce2624dba442ae9bb04a5eeccd8aaef02f52ff2

The lua version doesn't work. @tversteeg
