### ISSUE TITLE
registers.nvim breaks iabbrev commands with <C-R>

### ISSUE THREAD

**Issue by andrewferrier** [tversteeg/registers.nvim#36]
I have an `iabbrev` like this:

    iabbrev DATE <C-R>=strftime("%F")<CR>

It inserts the date when I type `DATE`. With https://github.com/junegunn/vim-peekaboo, this works. However, with `registers.nvim`, this abbrevation breaks; when I press space after `DATE`, I go to the command line with just `=` shown.

My `registers.nvim` configuration is:

    let g:registers_show_empty_registers=0
    let g:registers_hide_only_whitespace=1
    let g:registers_delay=500

**Comment by jose-elias-alvarez** [comment]
I'm having a similar issue where `<C-r>` in command mode doesn't work, e.g. when using `<C-r><C-w>` to insert the current word under the cursor. I believe the issue is in 3ce2624dba442ae9bb04a5eeccd8aaef02f52ff2, since the previous commit works.

**Comment by jose-elias-alvarez** [comment]
> @jose-elias-alvarez the command mode was a mistake I made by accidentally committing a WIP state for #32.

Fixed, thank you!

**Comment by andrewferrier** [comment]
Perfect, looks to work, thank you!
