### ISSUE TITLE
Keymappings are not set if file is opened by ":edit …" or Telescope.

### ISSUE THREAD

**Issue by timtro** [tversteeg/registers.nvim#42]
Thanks in advance.

I was having issues related to [Issue 40](https://github.com/tversteeg/registers.nvim/issues/40) that you fixed in yesterday's update. I have updated, but I'm now having a strange problem where the keymappings aren't set for any file opened after nvim has started. So if I open a file from the command line `> nvim /path/to/file`, there are no problems. But if I cold-start nvim and then either `:edit /path/to/file` or open by [Telescope](https://github.com/nvim-telescope/telescope.nvim), the keymappings aren't set.

I noticed that in the updated release you also made [changes](https://github.com/tversteeg/registers.nvim/issues/41) to the way the keymappings are run. Is that possibly the origin of the problem?

### Some details:
I'm using packer and I don't do anything fancy for loading:
```
  use 'tversteeg/registers.nvim'
```
If I open a file from the command line, there are no problems. But when I open nvim from my project directory and use telescope to find and open a file, or `:e /path/to/file`, the keybindings aren't set, but the plugin seems to be loaded. I can run `:Registers` and get the popup window, or even
```
:lua require'reigsters'.registers()
```
But the behaviour with `"` (in V or N mode) or `<C-r>` (in I mode) is as plain nvim.

Let me know if I can help.

```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gauiiQ/neovim-0.6.0~ubuntu1+git202109271150-96614f84a-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-gauiiQ/neovim-0.6.0~ubuntu1+git202109271150-96614f84a-adeb5640f/build/config -I/build/neovim-gauiiQ/neovim-0.6.0~ubuntu1+git202109271150-96614f84a-adeb5640f/src -I/build/neovim-gauiiQ/neovim-0.6.0~ubuntu1+git202109271150-96614f84a-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-gauiiQ/neovim-0.6.0~ubuntu1+git202109271150-96614f84a-adeb5640f/build/src/nvim/auto -I/build/neovim-gauiiQ/neovim-0.6.0~ubuntu1+git202109271150-96614f84a-adeb5640f/build/include
Compiled by buildd@lgw01-amd64-024

Features: +acl +iconv +tui
See ":help feature-compile"
```

Some things I've tried:
 - `$> nvim foo.txt`  *vs* `$> nvim` then `:e foo.txt`. Keybindings are no loaded in the latter case.
 -  I tried using packer to load the package on keypress as in [Issue 41](https://github.com/tversteeg/registers.nvim/issues/41). It made no difference.
 - This is *strange*. If I open a file so that the mappings aren't loaded, and then I manually source `registers.vim` (where the mappings are set), then nothing happens. (The neovim instance isn't fixed.)

**Comment by OmanF** [comment]
Not sure if `nvim-tree.lua` plugin uses either `:edit` and/or `Telescope` under the hood, but the same issue, default keybinding not working _anymore_, also happens when you open a file via that plugin.

**Comment by tversteeg** [comment]
I've added them to an autocmd with `BufEnter *`, this fixes it for me when I use `:e file`. Can you verify that it also fixes it in the other situations?
