### ISSUE TITLE
Make a border line around window

### ISSUE THREAD

**Issue by ivankovnatsky** [tversteeg/registers.nvim#44]
Would be great to have border line around the register window pop-up: 

![image](https://user-images.githubusercontent.com/75213/142919535-f9d26ad1-3cca-4598-a77e-82b0050bb950.png)

this is taken from fzf.vim/Buffers window.

**Comment by tversteeg** [comment]
There's a `let g:registers_window_border = "single"` [option](https://github.com/tversteeg/registers.nvim#setup). Is that not sufficient?
