### ISSUE TITLE
Feature Request: Automatically paste after selecting register in normal mode

### ISSUE THREAD

**Issue by kevintraver** [tversteeg/registers.nvim#47]
It would be helpful to have an option to automatically insert the register after selecting it in normal mode after using the `"` command and selecting the register.

Happy to help with a PR.

**Comment by kevintraver** [comment]
Looks like you can set the *mode* here:

https://github.com/tversteeg/registers.nvim/blob/4d1f3525c6f9be4297e99e6aed515af3677d7241/plugin/registers.vim#L13

So, for now I can just remap the key.

```vim.api.nvim_set_keymap('n', '"', [[<cmd>lua require'registers'.registers('')<cr>]], {} )```

**Comment by tversteeg** [comment]
Does this actually work?

I was planning on adding this feature somewhere this week.

**Comment by kevintraver** [comment]
Yes, works great.

**Comment by kevintraver** [comment]
Thanks! 👍
