### ISSUE TITLE
Feature request: hide the window after the action key is pressed

### ISSUE THREAD

**Issue by piotr-machura** [tversteeg/registers.nvim#48]
Hello, I have switched to this from [peekaboo](https://github.com/junegunn/vim-peekaboo) and I have to say the floating window is far superior to peekaboo's janky splits. The only difference is that peekaboo highlights the register after choosing it and closes only when the "action" key (sey `p` for paste) is pressed. This makes me not-forget which register I am using and it would be great to have an option for that here.

Here is exactly what I mean:
1. After `"` is pressed the window pops up as it does now.
2. A register key is pressed, say `a`. This moves the cursor to highlight register `a` and the window **does not close**. If the register is selected "manually" (with `<C-j>`/`<C-k>` or arrow keys and confirmed with `<CR>`) the window also stays open, waiting for the "action" key.
3. An "action" key is pressed, say `p`. The window closes and the register contents are pasted into the working buffer.

This could be a separate option, say `vim.g.registers_close_after_select`, defaulting to 1 (the current behavior). There could also be a separate highlight group, say `RegistersSelected` to further emphasize the selected register before `p` is pressed (if you are feeling fancy).

Thanks again for making this plugin, it's making my life much easier!

**Comment by tversteeg** [comment]
Added an option to the table you can pass to `registers.apply_register` for this.
Example:

```lua
use {
	"tversteeg/registers.nvim",
	config = function()
		local registers = require("registers")
		registers.setup({
			bind_keys = {
				registers = registers.apply_register({ keep_open_until_keypress = true }),
			},
		})
	end,
}
```
