### ISSUE TITLE
Colon register not available

### ISSUE THREAD

**Issue by kflak** [tversteeg/registers.nvim#49]
Hi, and thanks for a wonderful plugin that actually makes me take advantage of the registers!

At the moment, it seems there is no way to access the `colon` register while using the plugin. Is there a way around this?

**Comment by salkin-mada** [comment]
interesting. here using and empty buffer, no filetype.
`:echo "666"` and then `":p` inserts **echo "666"** in my buffer, no problem.
![scrn-2021-12-31_16-13-43](https://user-images.githubusercontent.com/12082586/147829859-5f094551-79a3-4155-a81f-4151ddd82fe2.png)

**Comment by eirikblekesaune** [comment]
You can actually access the colon register by adding it to the regsiters list:
```
vim.g.registers_show = '*+\"-/_=#%.0123456789abcdefghijklmnopqrstuvwxyz:' -- which registers to show and in what order'
```
It is also possible to paste from it, but not using the colon keys, as this is overriden by the open command line mapping. If you want to paste from it you can navigate to it using e.g. arrow keys and hit enter.

I guess one hack solution is to do an autocmd override over the colon mapping, but I suspect some people wouldn't having their colon keys overridden bya anything. Maybe a better solution would be to make an autocmd mapping for escaping the colon mapping, e.g. hitting `\:` while in the menu to paste from the colon register?

**Comment by salkin-mada** [comment]
sorry.. i was using `registers.nvim` (and thought i still was). But just checked my config - hehe. The former comment is to be disregarded .. i am on `which-key.nvim` these days

**Comment by tversteeg** [comment]
> You can actually access the colon register by adding it to the regsiters list:
> ```
> vim.g.registers_show = '*+\"-/_=#%.0123456789abcdefghijklmnopqrstuvwxyz:' -- which registers to show and in what order'
> ```
> It is also possible to paste from it, but not using the colon keys, as this is overriden by the open command line mapping. If you want to paste from it you can navigate to it using e.g. arrow keys and hit enter.
> 
> I guess one hack solution is to do an autocmd override over the colon mapping, but I suspect some people wouldn't having their colon keys overridden by anything. Maybe a better solution would be to make an autocmd mapping for escaping the colon mapping, e.g. hitting `\:` while in the menu to paste from the colon register?

It looks like I juat forgot to add it to the `vim.g.registers_show` list when implementing that. I'll add it once I'm available again.
