### ISSUE TITLE
Consider adding a minimalistic border line for `registers_window_border`

### ISSUE THREAD

**Issue by ivankovnatsky** [tversteeg/registers.nvim#50]
Maybe it's just me, but could not fancy none of the list, sorry.

This example is showing just a thin border line, if you think that makes sense to implant something like this, hat would be great. 

![image](https://user-images.githubusercontent.com/75213/147836537-a329e9b8-a85f-43f4-b469-96127cd1215b.png)

**Comment by tversteeg** [comment]
The screenshot you posted is of a different plugin. I dont understand exactly what you mean, sorry..

**Comment by ivankovnatsky** [comment]
> The screenshot you posted is of a different plugin. I dont understand exactly what you mean, sorry..

I would like to have some thin border line, like in fzf-vim plug-in pop-windows.

**Comment by tversteeg** [comment]
You can get this with the following configuration:

```vim
let g:registers_window_border = "rounded"
```

**Comment by ivankovnatsky** [comment]
any way to remove those think white lines? 

![image](https://user-images.githubusercontent.com/75213/147913057-6232145e-6355-42c3-98d1-50e72c3ee7cc.png)

**Comment by tversteeg** [comment]
You can change the highlight of the float border with:

```vim
hi FloatBorder ctermbg=white guibg=white
```
