### ISSUE TITLE
"Clipboard: no provider" error message when used on headless hosts

### ISSUE THREAD

**Issue by prg318** [tversteeg/registers.nvim#52]
When using this awesome plugin on a headless machine that's not running X11 or wayland (or any clipboard proxying SSH magic), the following error message is displayed by neovim (version 0.6.1) when opening the registers.nvim UI:

    clipboard: No provider. Try ":checkhealth" or ":h clipboard".
    clipboard: No provider. Try ":checkhealth" or ":h clipboard".
    Press ENTER or type command to continue

Nothing in my configuration sets the clipboard, but it seems to be upset that an X11/wayland clipboard tool is not available.  Ideally, the plugin should continue without warning and use the neovim internal clipboard

Steps to reproduce:
1. Create a chroot or VM and install latest nvim
2. Add registers.vnim to config
3. Try to open registers panel without installing X11 or wayland

Let me know if there is anything else I can do to help with this.  Thanks!

**Comment by tversteeg** [comment]
I've looked into it, but I couldn't find a way to detect whether a clipboard register is available. It would be greatly appreciated if anyone has any tips regarding detecting this.

**Comment by Creling** [comment]
We could avoid this error message by disabling clipboard totally, adding following snippet to `init.vim`:

```vim
let g:clipboard = {"name": "void", "copy": {}, "paste": {}}
let g:clipboard.copy["+"] = {-> v:true}
let g:clipboard.paste["+"] = {-> []}
let g:clipboard.copy["*"] = g:clipboard.copy["+"]
let g:clipboard.paste["*"] = g:clipboard.paste["+"]
```

**Comment by kkanhere** [comment]
Can a setting be added to turn off the clipboard register handling by the plugin? Or better if '+' is not listed in the g:registers_show variable then the plugin doesn't deal with the clipboard register.

**Comment by kkanhere** [comment]
Actually removing '+*' from g:registers_show config does seem to work. So kindly ignore the above comment and thanks!
