### ISSUE TITLE
Configurable popup window opts

### ISSUE THREAD

**Issue by wookayin** [tversteeg/registers.nvim#54]
Hello! Thanks for writing a great plugin.

It would be nice if users are allowed to make a customization on the floating window: currently many options are hard-coded in https://github.com/tversteeg/registers.nvim/blob/main/lua/registers.lua#L143-L153. For example, `style` or `border`, etc. as done in many other plugins involving floating windows.

**Comment by tversteeg** [comment]
This is a good idea, do you have an example of a plugin where it's configurable? I would like my implementation to be consistent with other plugins, if possible.
