### ISSUE TITLE
Feature request: paste in normal mode only when selecting with enter

### ISSUE THREAD

**Issue by ofirgall** [tversteeg/registers.nvim#55]
`let g:registers_paste_in_normal_mode = 1` lets you paste in normal mode but it always paste, if `"a` is pressed its pasting the content of `"a`.
I want an option that let you use copy registers as normal but still let you browse the registers and paste them if you want.

The option can be selected with `let g:registers_paste_in_normal_mode = 2`

**Comment by tversteeg** [comment]
So if I understand it correctly you want the following when `registers_paste_in_normal_mode = 2` (or something else, I use 0 and 1 as booleans here):

-  `"` opens the popup
- If a register is selected with <kbd>Return</kbd>:
	- Paste the contents
- If the register key is pressed, e.g. <kbd>A</kdb>:
	- Use the default behavior, setting the registers for further actions

**Comment by ofirgall** [comment]
Exactly! Thanks for the quick reply!
