### ISSUE TITLE
registers.nvim conflicts with telescope.nvim

### ISSUE THREAD

**Issue by yamada-wacul** [tversteeg/registers.nvim#56]
This is reporting work-around. 

`i_<C-R>` is default map to call registers.
So when we put `i_<C-R>` to call registers from telescope.nvim prompt, this plugin kills the window of telescope.nvim.

In such case, we should suppress `imap <C-R>` and set new map like this:

```lua
vim.g.registers_insert_mode = false -- Suppress imap <C-R>
vim.cmd([[
    imap <buffer> <expr> <C-R> &ft=='TelescopePrompt' ? '<C-R>' : registers#peek('<C-R>')
]])
```

Could you put this guide on your README.md?

**Comment by tversteeg** [comment]
I've added this in #68, so it doesn't need to be added manually anymore.
