### ISSUE TITLE
The popup windows only show a small part

### ISSUE THREAD

**Issue by winkee01** [tversteeg/registers.nvim#60]
### Please select which platform you are using.

Mac

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

so the popup window always starts from the current line where the cursor is at?
If the cursor is at the bottom, then the popup window only shows a small part of it. Is there any option to config where to display the popup window?
<img width="1061" alt="CleanShot 2022-05-08 at 00 11 13@2x" src="https://user-images.githubusercontent.com/49930785/167262753-065c7ba0-a70e-4ce3-a217-219a4084234c.png">

**Comment by tversteeg** [comment]
Fixed in #68.
