### ISSUE TITLE
registers.nvim conflicts with use of <C-R> in iabbrev RHS

### ISSUE THREAD

**Issue by andrewferrier** [tversteeg/registers.nvim#61]
### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

To recreate:

* Install and configure registers.nvim
* Add an abbrevation to init.vim or similar `iabbrev XYZ <C-R>=2*3<CR>`
* Open an empty file, type `XYZ `. NeoVim shows an error about a recursive mapping

I suspect this is because `registers.nvim` captures `<C-R>` somehow.

**Comment by tversteeg** [comment]
What version of Neovim are you using? I can't reproduce this with the latest nightly version.

**Comment by andrewferrier** [comment]
Let me double-check and post here. I'll try and create a recreation `init.lua` too.

**Comment by andrewferrier** [comment]
OK, as luck would have it, I now cannot reproduce! Sorry for the wasted time. I think you can close this for now.

Thanks for your work on this plugin!

**Comment by tversteeg** [comment]
No problem!
