### ISSUE TITLE
It breaks with multi column selection

### ISSUE THREAD

**Issue by lourenci** [tversteeg/registers.nvim#70]
### Please select which platform you are using.

Mac

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

First of all, thanks for this plugin. 

In visual mode, with some columns selected, pasting from `registers` to replace the selected content does not work.

**selection (before applying some register to replace the selected content):**
<img width="350" alt="image" src="https://user-images.githubusercontent.com/2339362/193434436-fcae6e31-4b9e-435d-aaac-05cba3dfb10d.png">

**`"0p` without this plugin (how it is supposed to work):**
<img width="420" alt="image" src="https://user-images.githubusercontent.com/2339362/193434515-c6b2d26d-0b2b-4ad9-b5a5-1dedd7575681.png">

**`"0p` with this plugin:**
<img width="402" alt="image" src="https://user-images.githubusercontent.com/2339362/193434486-6f86a081-04d3-44ac-895e-de988d6b8d72.png">

**Comment by tversteeg** [comment]
I have fixed this in the latest commit, can you verify that it works?

**Comment by lourenci** [comment]
It worked like a charm. Tks.
