### ISSUE TITLE
Option to stop showing fed keys?

### ISSUE THREAD

**Issue by Frederick888** [tversteeg/registers.nvim#73]
### What would you like registers.nvim to be able to do?

In normal mode, e.g. `"ap`, it currently prints out `"a` in command output: https://github.com/tversteeg/registers.nvim/blob/d155742d5727373be0b484e87a0635348bbe2895/lua/registers.lua#L766

I think it'd be nice to provide an option to disable this. It especially doesn't play well with `set cmdheight=0`.

### If you have any ideas on how this should be implemented, please tell us here.

If not really needed, perhaps we can even just remove this line?

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by tversteeg** [comment]
Thanks for noticing it, this was a leftover debug printing line I forgot to remove 😅
