### ISSUE TITLE
Unable to paste from `"` in insert mode using `<C-R>`

### ISSUE THREAD

**Issue by lourenci** [tversteeg/registers.nvim#74]
### Please select which platform you are using

Mac

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

In `ctrl-r` mode, when trying to insert from `"` register, the following error happens:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/2339362/193752460-e4eddfb7-cb21-4372-b6c3-a4590dd01620.png">

Thanks for the plugin, btw.

### Neovim version

```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

### Setup

```lua
local registers = require("registers")
registers.setup({
	register_user_command = false,
	system_clipboard = false,
	show_register_types = false,
	show_empty = false,
	bind_keys = {
		return_key = false,
		ctrl_n = false,
		ctrl_p = false,
		ctrl_j = false,
		ctrl_k = false,
	},
	window = {
		highlight_cursorline = false,
		border = "rounded",
	},
})
```

**Comment by tversteeg** [comment]
Very odd that you're having so many problems, I also can't reproduce this one. Are you using `<C-R>` from any irregular place?

**Comment by lourenci** [comment]
Nope. Using it in a normal buffer. 😢 I just have tried again:
1. In a normal buffer, entered in insert mode.
2. `<C-R>"`

The weird thing is that this just happens with pasting from `"`; the other ones work just fine. Maybe some specific to my `registers.setup()`? 🤷🏻‍♂️

**Comment by tversteeg** [comment]
Yeah that's exactly what I tried as well, I have a feeling it might be related to #71, since they also use a Mac and have some weird issues I can't reproduce…

**Comment by tversteeg** [comment]
Did the latest commit fix this issue by any chance?

**Comment by lourenci** [comment]
Nope. 😢

**Comment by lourenci** [comment]
No problem with the `head@master` anymore.
