### ISSUE TITLE
Vim(let):E716: Key not present in Dictionary: "rhs"

### ISSUE THREAD

**Issue by Karmenzind** [tversteeg/registers.nvim#75]
### Please select which platform you are using

Linux

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

NVim raised error when I pressed `"`.

![image](https://user-images.githubusercontent.com/17923071/195138469-07aa8fe1-7967-4a92-9fd1-3581d7c9178a.png)

Then it kept showing this error. I had to kill the shell to close NVim.
![image](https://user-images.githubusercontent.com/17923071/195139279-2cbd900b-db64-42d0-b080-667132ee3130.png)

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Setup

```lua
local registers = require("registers")

// Nothing. I just leave it empty.
registers.setup({})
```

**Comment by tversteeg** [comment]
Thanks for the bug report. There have been some changes in the mean time, are you still experiencing this problem?

**Comment by Karmenzind** [comment]
@tversteeg It worked fine now. Thanks.
