### ISSUE TITLE
"Registers window isn't open, can't apply register" on first yank after opening nvim

### ISSUE THREAD

**Issue by Penaz91** [tversteeg/registers.nvim#77]
### Please select which platform you are using

Linux

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Greetings,

I've made a habit in my workflow to quickly copy/paste into the "+" register after opening nvim (usually in different terminals).

When I try to yank a line or a visual selection the window pops up but an error is echoed in the status line:

![img-2022-10-24-102937](https://user-images.githubusercontent.com/6682630/197482609-2a5822ab-27dd-42fd-9833-e69362f19bfd.png)

This wasn't a problem some time ago. It seems I need to retry copying a couple times before it works.

Thank you for your attention.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Setup

```lua
require("registers").setup({
    show_empty = false,
    window = {
        border = "double"
    }
})
```

**Comment by tversteeg** [comment]
Thanks for the bug report, I do notice this sometimes, but I can't consistently reproduce it.

Any suggestions on how to consistently reproduce this would be greatly appreciated!

**Comment by Penaz91** [comment]
I noticed that I can reproduce it by pressing the "+y combination very quickly.
Maybe the window isn't registered as "open" yet as I'm finishing thebcombination?

**Comment by tversteeg** [comment]
That's a good clue, there's a small time frame between waiting for the keypress and opening the window and registering the keybinds. I think I'll have to rewrite that part and that should solve your problem.

**Comment by tversteeg** [comment]
It should work now, can you verify that that's the case?

**Comment by Penaz91** [comment]
It seems that it's working correctly, I will let you know if the issue pops out again. Thank you!
