### ISSUE TITLE
Allow args in user_command to open register in specific mode

### ISSUE THREAD

**Issue by tobealive** [tversteeg/registers.nvim#82]
### What would you like registers.nvim to be able to do?

Extending the `Registers` command to accept args to open the window in a specific mode.

### If you have any ideas on how this should be implemented, please tell us here.

I can submit a PR. Changes should be minimal to make this possible.

As an alternatively we could make sure the `show_window` function is accessible.
e.g., `:lua require "registers".show_window { mode = "motion" }` currently won't open the window. I didn't investigated why this is yet.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by tversteeg** [comment]
I would like both things: the arguments for `:Registers` and a more dynamic `show_window`.

**Comment by tobealive** [comment]
Oh nice things can be so easy.

That perfectly serves the purpose.

Thanks alot! @tversteeg
