### ISSUE TITLE
Insert mode preview doesn't get disabled with preview = false

### ISSUE THREAD

**Issue by andrewferrier** [tversteeg/registers.nvim#86]
### Please select which platform you are using

Mac

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

`preview = false` doesn't seem to affect `Ctrl-R`.

Even with `preview=false` set, when I enter insert mode and hit `Ctrl-R`, I see a preview of the 'about-to-be-entered' text in the buffer (which changes as I scroll with `<Up>` and `<Down>`.

`registers.nvim` commit 9281a0e49cd5acdb551dcc

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info

### Setup

```lua
require("registers").setup({                             
    preview = false,                                     
    show = "*-/#%.0123456789abcdefghijklmnopqrstuvwxyz", 
    show_empty = false,                                  
    trim_whitespace = true,                              
    window = { border = "rounded", transparency = 0 },   
})
```

**Comment by tversteeg** [comment]
That's because `preview = false` isn't an option I'm using anymore. You can disable it instead with:

```lua
events = {
	on_register_highlighted = false
}
```

**Comment by andrewferrier** [comment]
Thanks. OK, in that case I would suggest there's probably a doc fix that's needed, as it's still present: https://github.com/tversteeg/registers.nvim/blob/9281a0e49cd5acdb551dccf38a36db55156f7990/doc/registers.txt#L46. That's where I found it from.

**Comment by tversteeg** [comment]
Ah I see, I was wondering where you get that from, thanks!

**Comment by andrewferrier** [comment]
No problems. Thanks for all your hard work on this great plugin!
