### ISSUE TITLE
Consider to use xnoremap instead of vnoremap

### ISSUE THREAD

**Issue by tami5** [tversteeg/registers.nvim#9]
Hey @tversteeg awesome plugin, I wanted to point out that perhaps using xnoremap is better that vnoremap. vnoremap from my experience  breaks replace feature in snippet and auto-completion.

https://github.com/tversteeg/registers.nvim/blob/b8f6283724d3ccacf2c7add61f3fcb9c02e7d61d/plugin/registers.vim#L22

**Comment by tversteeg** [comment]
Thanks for the suggestion!
