### ISSUE TITLE
Custom Key Mapping under `"`

### ISSUE THREAD

**Issue by zhou13** [tversteeg/registers.nvim#91]
### What would you like registers.nvim to be able to do?

It seems that there is no way to create a customized keymap for the `:Registers` window. I want to use `<C-C>` to close the register window instead of `<ESC>`. But it seems it is not easily doable right now.

### If you have any ideas on how this should be implemented, please tell us here.

It will be ideal if we can do something like
```
require("registers").setup({ bind_keys = { "<C-c>": "<Esc>" } })
```

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by tversteeg** [comment]
This is a good idea, I made it so any key can be bound to the functions, see the default bindings in README.md. Can you verify that this properly works?

**Comment by zhou13** [comment]
Thanks! This works great.
